version: "3.5"
services:
  app:
    build: .
    environment:
      COLLECTION_NAME: ${COLLECTION_NAME}
      CONNECTION_STRING: ${CONNECTION_STRING}
      DB_NAME: ${DB_NAME},
      UNSPLASH_ACCESS_KEY: ${UNSPLASH_ACCESS_KEY}
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /root/app:/data/db
    ports:
      - "27117:27017"
