version: "3.5"
services:
  app:
    build: .
    environment:
      CONFIGURATIONS_COLLECTION_NAME: ${CONFIGURATIONS_COLLECTION_NAME}
      CONNECTION_STRING: ${CONNECTION_STRING}
      UNSPLASH_ACCESS_KEY: ${UNSPLASH_ACCESS_KEY}
      IMAGE_MANIPULATION_SERVICE_URL: ${IMAGE_MANIPULATION_SERVICE_URL}

  imagemanipulation:
    build: ../image-manipulation-service/

  markov:
    build: ../markov-service/

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /root/app/mongo-data/:/data/db
    ports:
      - "27117:27017"

networks:
  app:
